# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":794,"y":163,"deletable":false,"next":{"block":{"type":"variables_setup_imported_function","id":"P;gttZ]0._t5xjOS=#W=","fields":{"FROM_MODULE":"robot_lqr","VAR":{"id":",z*R?zA!N0rS]#1Fo$r|"}},"next":{"block":{"type":"variables_setup_object_instance","id":"NJP.OCU(#q#f-93kB)(5","extraState":{"optionLevel":0},"fields":{"VAR":{"id":"@h?s}-OgvWhzCsqUE?g+"},"CLASS_NAME":"RobotLQR"}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":150,"y":300,"deletable":false,"next":{"block":{"type":"blockObjectInstanceCallStatement","id":"d5#T+-M9QcU,xD0KIowd","extraState":{"optionLevel":1},"fields":{"CALL_TYPE":"CLASS_CALL_METHOD_SYNC","METHOD":"andar_cm"},"inputs":{"VAR":{"shadow":{"type":"variables_get_object_instance","id":"r{vTDKEj*Jr^CiHH[Mn[","fields":{"VAR":{"id":"@h?s}-OgvWhzCsqUE?g+","name":"robot","type":"ObjectInstance"}}}},"ARG0":{"shadow":{"type":"blockMathNumber","id":"%*.]L2FpGK**~WqQDwWW","fields":{"NUM":10}}}},"next":{"block":{"type":"blockObjectInstanceCallStatement","id":"p0kPj#8A6*:39wmLq3)0","extraState":{"optionLevel":1},"fields":{"CALL_TYPE":"CLASS_CALL_METHOD_SYNC","METHOD":"virar"},"inputs":{"VAR":{"shadow":{"type":"variables_get_object_instance","id":"xLTJ]z{m|!bV2)OoA0B|","fields":{"VAR":{"id":"@h?s}-OgvWhzCsqUE?g+","name":"robot","type":"ObjectInstance"}}}},"ARG0":{"shadow":{"type":"blockMathNumber","id":"O*^T5TQ+DPf_cd#@CEj5","fields":{"NUM":90}}}}}}}}}]},"variables":[{"name":"red","id":"J:[}3KS2Erb9[4Efh,pt","type":"ColorDef"},{"name":"orange","id":"tft23hQ[d.f;ugst~K`O","type":"ColorDef"},{"name":"yellow","id":"`GuC?soLvGLOu=^}E.}U","type":"ColorDef"},{"name":"green","id":"!b=;Iz7!-UTNW0yU+~vB","type":"ColorDef"},{"name":"cyan","id":"Fv6o3i@w`EAyf5.0zF*5","type":"ColorDef"},{"name":"blue","id":"`m%X37yXE;c]Sz@k~j_I","type":"ColorDef"},{"name":"violet","id":"O;MG37?%{cwu-gE=eKQ0","type":"ColorDef"},{"name":"magenta","id":"~;QM8PgVAqk^~G=~.)NN","type":"ColorDef"},{"name":"white","id":"[@L?^++(n~{OorxQB):j","type":"ColorDef"},{"name":"none","id":"Ck0,.6f~ykM0CzGpV!J!","type":"ColorDef"},{"name":"RobotLQR","id":",z*R?zA!N0rS]#1Fo$r|","type":"FunctionImported"},{"name":"robot","id":"@h?s}-OgvWhzCsqUE?g+","type":"ObjectInstance"}],"info":{"type":"pybricks","version":"1.7.0"}}
from robot_lqr import RobotLQR

# Set up.
robot = RobotLQR()


# The main program starts here.
robot.andar_cm(10)
robot.virar(90)
